# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Deploy a new version to the Google Play"
  lane :production do
    gradle(task: "clean bundleRelease")
    notes = changelog_from_git_commits(merge_commit_filtering: "exclude_merges" )
    File.open(ENV["GITHUB_WORKSPACE"] + "/fastlane/metadata/android/en-US/changelogs/out.txt", "w") {|f| f.write(notes) }
    upload_to_play_store
  end
end
