# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Deploy a new version to the Google Play"
  lane :production do
  notes = changelog_from_git_commits(between: ["cba321d", "HEAD"], merge_commit_filtering: "exclude_merges" )
  puts(Dir.entries(ENV["GITHUB_WORKSPACE"]))
      out_file = File.new(ENV["GITHUB_WORKSPACE"] + "/fastlane/metadata/android/en-US/changelogs/out.txt", "w")
      out_file.puts(notes)
      out_file.close
    gradle(task: "clean bundleRelease")
    upload_to_play_store
  end
end
